import { ProductInfoType } from "@/types/types";

export const staticProductInfo: ProductInfoType[] = [
  {
    batchId: "1",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "2",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "3",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "4",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "5",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "6",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "7",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "8",
    dest: "USA",
    status: "Delivered",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "9",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
  {
    batchId: "10",
    dest: "USA",
    status: "InTransit",
    type: "Electronics",
    source: "China",
    id: "1",
    long: 37.7749,
    lat: -122.4194,
  },
];
